### ISSUE TITLE
module 'jsonrpc' has no attribute 'JsonRpc20'

### ISSUE THREAD

**Issue by slobLX** [diegma/graph-2-text#7]
When I run 'python3 sr11_onmtgcn_input.py -i ../data/srtask11/SR_release1.0/ -t deep -p test', the error occurs:
Traceback (most recent call last):
  File "sr11_onmtgcn_input.py", line 19, in <module>
    parseService = CoreNLPService()
  File "../utils/CoreNLPService.py", line 15, in __init__
    self.server = self.get_server()
  File "../utils/CoreNLPService.py", line 18, in get_server
    version = jsonrpc.JsonRpc20()
AttributeError: module 'jsonrpc' has no attribute 'JsonRpc20'

I am using python3.6

**Comment by Celeste-cj** [comment]
You could modify utils/__init__.py like this:

`
from utils.jsonrpc import *
__all__ = ["JsonRpc20"]
`

**Comment by FlameCharmander** [comment]
When I .utils.jsonrpc.RPCTransportError: [Errno 10061], does anybody have the same error?

**Comment by HZQ950419** [comment]
Have you fixed it? I have the same problem and I think this is because jsonrpc.py is python2 version.
